spring:
  application:
    name: security
  datasource:
    url: jdbc:oracle:thin:@dpedu.cuaavbbmvodr.ap-southeast-1.rds.amazonaws.com:1521:DPMS
    username: admin
    password: easy2log
    drive-class-name: oracle.jdbc.OracleDriver
  jpa:
    database: ORACLE  # Specifies the database type
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true # Formats SQL queries for better readability
        use_sql_comments: true  # Adds comments to the SQL logs (optional)


